# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20690db6445aae5050da20d989ba773b29df4fd8e806df3cb9788f54ccb729681a0688c69e38a77a6555b514d05dc911af38763eae3bc72b494615b022e547d1
test:
  secret_key_base: bfc1c0a9eb1e8bddb3073c4a668f951b2b3e7bee958ab387e65426b34fc723bde19c5e116654139c1724bb523f3c2e6c2b14ef695568281c3512f453e3a0a75f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
